### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by metalivedev** [jquery/sizzle#334] opened 2015-04-27 17:59 UTC
Please add a LICENSE file for external/mootools-slick

I tried to find a separate license file in the upstream https://github.com/mootools but could not find one. Consumers of your software need to know the license of your dependencies as well.

**Comment by scottgonzalez** [comment] 2015-04-27 18:05
It's hard to add a license file when the software itself doesn't ship with one. With that being said, MooTools is released under the terms of the MIT license.

**Comment by scottgonzalez** [comment] 2015-04-27 18:07
Also note that Sizzle itself has no dependency on this code, it's only used for tests.

**Comment by metalivedev** [comment] 2015-04-27 19:47
Ok, I've posted a license request upstream as well, https://github.com/mootools/slick/issues/78

Thank you for your attention and for the information about how `slick` is used (in testing only). That would be non-trivial work for an auditor to determine though, so I think an explicit license file would still be beneficial. Your own license indicates that users should review the license files of the external dependencies, yet you neither point at the source of this dependency (`slick`) nor list a License file explicitly. Sorry, I know this is annoying but licensing is important, especially for open source projects.

**Comment by mzgol** [comment] 2015-04-27 20:25
@metalivedev How do you use Sizzle? If you download it via bower or npm then you won't see the `external` directory, you need to explicitly clone the Sizzle repository to have this problem.

That said, I'd have nothing agains including LICENSE files in the `external/*` directories but they should come from official repos.

**Comment by scottgonzalez** [comment] 2015-04-27 20:27
> That said, I'd have nothing agains including LICENSE files in the external/* directories

This is what we already do in all projects. The problem is that slick doesn't have a license file (nor is the license included in the code), which is a violation of its own license...

**Comment by gibson042** [comment] 2015-04-29 17:30
I'm going to close this for now. Please request reopening if/when something changes upstream.

**Closed by gibson042** 2015-04-29 17:30 UTC

**Comment by gibson042** [comment] 2018-11-13 05:05
Sizzle has had a license since 1.0.0: 5cdcc43d5c64c9eb25b88b9652fdc3e53a6be3bd

For anything more consequential than that pointer, though, I think I must direct you to the JS Foundation.
