### ISSUE TITLE
Sizzle implementation in jQuery 

### ISSUE THREAD

**Issue by ldragoncg** [jquery/sizzle#329] opened 2015-03-30 19:38 UTC
Firefox debuger and Firebug reports error when parsing XML files.
Firefox ver. 36.0.4 / Firebug ver. 2.0.8
**Firefox debuger:**   parsing error in chrome://browser/content/devtools/webconsole/xul#
**Firebug:**   није добро формиран (parsing error)
>...4'\>\</a\>\<select id='sizzle1427741704334-]' msallowcapture=''\>\<option selected='...
>--------------------------------------------------------^

The catch is in sizzle implementation on line 1176 of jQuery 2.1.3 ( same is for ver. 1.11.2)
>line is:                   **"\<select id='" + expando + "-\\f]' msallowcapture=''\>" +**
>where sizzle line is: **"\<select id='" + expando + "-\\r\\\\]' msallowcapture=''\>" +**

For some reason, even **'\\f\\\\'** doesn't help, but with **'\\r\\\\'** it works fine. Also works with other #whitespace characters ([\\x20\\t\\n]).

**Comment by gibson042** [comment] 2015-03-30 21:13
Duplicate of #304. This will be fixed in the next version of Sizzle, and in jQuery 3.0.

**Closed by gibson042** 2015-03-30 21:13 UTC
