### ISSUE TITLE
$element.is(':focus') does not work on mobile Chrome (maybe Webkits in general)

### ISSUE THREAD

**Issue by func0der** [jquery/sizzle#385] opened 2016-08-05 12:31 UTC
It seems that the $element.is(':focus') detection of jQuery and therefore Sizzle has troubles detecting the currently focused element in the Android version of the Chrome browser.

I have created fiffdle for this problem: https://jsfiddle.net/abcqLoaL/1/

I had the same issue in Safari on an iOS device. Maybe this is a webkit related problem.
Firefox works fine though. Desktop browser seem to handle it fine.

**Comment by dmethvin** [comment] 2016-08-05 12:41
Looks like Chome fixed this bug at some point but the Webkit-based browsers still have it?

https://github.com/jquery/sizzle/blob/b05a9d37fd0c237d56736749f1a83c147fca1cb6/src/sizzle.js#L705-L709

**Comment by func0der** [comment] 2016-08-05 12:44
I have Chrome 43 installed on my test phone. It does not seem to be fixed in it.

**Comment by dmethvin** [comment] 2016-08-05 12:47
Interesting, it works on desktop Chrome 52. In any case, that comment explains why it can't be fixed in Sizzle without causing IE8/9 to throw errors, which is worse.

**Comment by func0der** [comment] 2016-08-05 12:54
Yeah, it is not problem on desktop browsers.
It only occurs on mobile browsers.
I just got my hands on a Chrome 52 Android browser in which this problem seems to be fixed.
The Safari still had the issue.

So we leave this broken for some browsers? No workaround or double check here?

**Comment by mgol** [comment] 2016-08-05 13:00
We'd need to know what to check and do a proper support test. The problem is we can't test focus-related things because we'd have to hijack the focus of the whole page and that's too disruptive.

Yes, there are cases that we're unable to workaround because there are no reliable detection ways and we try to avoid user agent sniffing.

If we know that the IE 8/9 issue is really only applicable to IE<10 (what about IE 6/7?), we might need to do an ugly check for `document.documentMode` here.

**Comment by func0der** [comment] 2016-08-05 13:29
That's too bad.
I though the support for such browsers (6/7) gets dropped over time, because of the hassle of keeping it up.

So the only way to avoid this issue is on the developers end by checking for !broken IE versions and use `$element.is(window.activeElement)` in that case.

**Comment by mgol** [comment] 2016-08-05 13:35
@func0der Sizzle has broader browser support than jQuery; see https://github.com/jquery/sizzle/wiki#-browser-support

**Comment by mgol** [comment] 2016-08-05 13:35
@func0der Sizzle has broader browser support than jQuery; see https://github.com/jquery/sizzle/wiki#-browser-support. jQuery browser support is available at https://jquery.com/browser-support/

**Comment by markelog** [comment] 2016-08-06 01:06
Yeah, that's weird we still want to support those browsers :/. I'm sure @gibson042 has some reasons for it though. 

I vote is just to drop it

**Comment by mgol** [comment] 2023-09-07 12:15
FWIW, I checked on Safari on iOS 16.6 and on Chrome 114 on Android (the latter via BrowserStack) and I don't see the issue in either of them; closing.

**Closed by mgol** 2023-09-07 12:15 UTC
